/*======================================================================================================
	C++ class definitions exported from UnrealScript.
	This is automatically generated by the tools.
	DO NOT modify this manually! Edit the corresponding .uc files instead!
	Ok you can modify it manually, but be smart about it. Backups.

	No clue how you exported .uc to .h. Lemme leverage the smartness anyway!
	https://www.oldunreal.com/phpBB3/viewtopic.php?f=37&t=3938&sid=8b71815f24b4bc324870936b455f4dbd
========================================================================================================*/
#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (push,4)
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

#ifndef NAMES_ONLY

class ACDDiscordActor : public AActor
{
public:
	DECLARE_FUNCTION(execTestFunction)
		DECLARE_CLASS(ACDDiscordActor, AActor, 0, ChatDiamond);
	ACDDiscordActor();
};

#endif

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif // NAMES_ONLY

#if ((_MSC_VER) || (HAVE_PRAGMA_PACK))
#pragma pack (pop)
#endif

#ifdef VERIFY_CLASS_SIZES
VERIFY_CLASS_SIZE_NODIE(ACDDiscordActor)
#endif // VERIFY_CLASS_SIZES